install:
- pip install --user awscli
- wget https://github.com/gohugoio/hugo/releases/download/v0.83.0/hugo_0.83.0_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- hugo version
before_script:
- rm -rf public
- hugo
script:
- aws s3 sync public/ s3://docsmatter.org --acl public-read --delete
- aws cloudfront create-invalidation --distribution-id E6EMLN80H6IQQ --paths '/*'
branches:
 only:
 - main
